{% set version = "0.1" %}

package:
  name: otrobopt
  version: {{ version }}

source:
  fn: otrobopt-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otrobopt/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 7ea2d3e321a2aae80d7361074627029490202ad33a03b557014b38393bb13c9a  # [not win]

  fn: otrobopt-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otrobopt-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: 56851d54241b51a9140139656cb1c3fb1c7647393d2c5a563754a0ef6186e770  # [win32 and py27]

  fn: otrobopt-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otrobopt-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: fdfa728e40ce951d4831d058dca75dec305fe9e69ae432a6aceae7153ae6e05f  # [win64 and py27]

  fn: otrobopt-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otrobopt-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  sha256: 7fada4327b090ba9d37d32bd2d8668a91bd405d41a173e8546d3d4138ff9a39d  # [win32 and py34]

  fn: otrobopt-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otrobopt-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  sha256: f2410ddf4fe10b658c0bf72e30985c3ec79d28861b3b4c27a4b0b8adfea4ee60  # [win64 and py34]

  fn: otrobopt-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otrobopt-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: cabfc815558f594d9d70a2cff4da37574a65ed1316f94b3cc374457d6f5e6ab4  # [win32 and py35]

  fn: otrobopt-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otrobopt-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: c8e304ef2a00581ee8156c33ac9b8a0c2e5af6998ce4057eb06d7bc29e4cf0da  # [win64 and py35]

build:
  number: 2

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - openturns  # [not win]

  run:
    - python
    - openturns

test:
  imports:
    - otrobopt

about:
  home: http://openturns.org/
  license: LGPLv3
  license_file: COPYING.LESSER  # [not win]
  summary: Robust optimization module

extra:
  recipe-maintainers:
    - jschueller
