travis:
  secure:
    BINSTAR_TOKEN: aNRn1/uJyG6xv9QtxIT9QlM73s7+ahntVAfpr7uAO6il2biULDIDW8VxI1jT15l46t/QUMoelDGPGqrptj1wwz+Dwtk6cERHYo2qHirVRZRFxobFW79ows6kG5MPZo5+Szt49jAHI1WnQalop/fT1nqCP1CILgCAswGLbJpM6kE+zEv1Ck7+kNsZddyP9M2NPyQKLAr9qSMRxLuOY7k2SywPzrcYx7ytOMMHND1iOJEq0R+wiLsIMj19B/EUYhCClQNfwBWxaypTiS9GtqmmjhLHrhmFEBJlEvjLUqjGpR6Nzq7uq8BCHTn83PVIm8f7X103/p1j7eymiREaoNSuQjxm3K4qNS+hnjNrsWNbNeO+Hi/tZXaMa3WhK+vKU5QV01Q+N9DcAjl0xg3DH7MzZssfBlKpZ5tRTLXZHIluSw3kQnxwvZXHIA5vHfTI1GOwwi0Oc9kXOxT5OXwohThmqjK5Exv1Ms7oVBuUL3AiI7+uKTY6yuLVRjIIMBDQSPwU+48YGvqNgoNpqte+sIr/CqAWck4N5vy5Tc5JnIBDCyHEHQHcImG+8l1L6P+2aeIWGaEzTUAdbaf7sVQGNYYnCRX70SZXAfrVv2ZoipXfo3O8y99O3NEZGWkL6mAnwAfTL2rYTJ16lJZ5cXUCwvfhAjoE0HD/0Yqp78MVypC02Bs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
